services:
  postgres:
    image: postgres:16
    container_name: leaseanddesist-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leaseanddesist
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: express-server
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/leaseanddesist?schema=public
      - CLIENT_ORIGIN=http://localhost:3000
      - JWT_SECRET=super-secret-key
      - JWT_EXPIRES_IN=15m
      - REFRESH_TOKEN_EXPIRES_IN_DAYS=7
      - ACCESS_TOKEN_EXPIRES_IN=15m
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - server-node-modules:/app/node_modules

  client:
    build: ./client
    container_name: react-client
    ports:
      - "3000:3000"
    command:
      - sh
      - -c
      - npm install && npm start
    environment:
      - VITE_API_BASE_URL=http://localhost:5002
    stdin_open: true
    tty: true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - client-node-modules:/app/node_modules

volumes:
  pg-data:
  server-node-modules:
  client-node-modules:
